name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.2', '8.3', '8.4', '8.5' ]
        dependency-version: [ prefer-stable, prefer-lowest ]
    name: P${{ matrix.php }} - ${{ matrix.dependency-version }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, gd, exif, fileinfo
          coverage: none

      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ runner.os }}-php${{ matrix.php }}-${{ matrix.dependency-version }}-${{ hashFiles('composer.json') }}
          restore-keys: composer-${{ runner.os }}-php${{ matrix.php }}-${{ matrix.dependency-version }}-

      - name: Install dependencies
        run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-progress

      - name: Run tests
        run: vendor/bin/pest

  static-analysis:
    runs-on: ubuntu-latest
    name: PHPStan

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, gd, exif, fileinfo
          coverage: none

      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ runner.os }}-php8.5-phpstan-${{ hashFiles('composer.json') }}
          restore-keys: composer-${{ runner.os }}-php8.5-phpstan-

      - name: Install dependencies
        run: composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --no-progress

  lint:
    runs-on: ubuntu-latest
    name: Pint

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, gd, exif, fileinfo
          coverage: none

      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ runner.os }}-php8.5-pint-${{ hashFiles('composer.json') }}
          restore-keys: composer-${{ runner.os }}-php8.5-pint-

      - name: Install dependencies
        run: composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      - name: Run Pint
        run: vendor/bin/pint --test